"""THEOREM (two slopes are never enough).
If every label used -- on edges and on generators -- lies in only two distinct
slope classes, then any object whose forcing succeeds has score >= 2.

Proof.  Write x, y for the two slopes.  They must be independent (P4).  Any
f in M is c^x (x) x + c^y (x) y with c^x, c^y in Q^V; vanishing of f at
v outside T u {e} forces c^x_v = c^y_v = 0 there.  tau = alpha x + beta y with
alpha, beta both nonzero (tau is parallel to neither), so forcing e needs
c^x_e != 0.  The module generated by the x-edges is exactly the set of
c summing to zero on every connected component of G_x, relaxed on components
carrying an x-generator; hence the G_x-component of e must contain a T-vertex
or an x-generator, and likewise for y.  Forcing therefore never cascades:
'liveness' of a component is fixed by T_0 and the generators alone.  So every
component of G_x must be live and every component of G_y must be live, giving
   m >= (n - a) + (n - b),    r >= max(0, a - t) + max(0, b - t)
with a, b the component counts.  In every case m + r >= 2(n - t).           []

This test checks the theorem numerically on random two-slope objects.
"""
import sys, os, random
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
from fractions import Fraction
from kakeya import ConstructibleGraph, build_rows, ZERO
from fastcore import force

random.seed(4242)
pairs = [((1, 0), (0, 1)), ((1, 1), (1, 2)), ((1, 0), (1, 3)), ((2, 1), (0, 1))]
checked = viol = 0
for trial in range(4000):
    x, y = random.choice(pairs)
    alpha = [ZERO, x, y]
    d = random.choice([[2], [3], [2, 2], [2, 3], [3, 2], [2, 2, 2], [4], [2, 4], [5]])
    doms = []
    for i in range(1, len(d) + 1):
        import itertools
        pref = list(itertools.product(*[range(1, d[j] + 1) for j in range(i - 1)]))
        doms.append([tuple(list(p) + [l]) for p in pref for l in range(1, d[i - 1])])
    f = [{k: random.choice(alpha) for k in dm} for dm in doms]
    f = [{k: v for k, v in fi.items() if v != ZERO} for fi in f]
    G = ConstructibleGraph([ZERO, x, y], d, f)
    verts = G.vertices(); n = G.n
    idx = {v: j for j, v in enumerate(verts)}
    R = [(random.choice(verts), random.choice([x, y]))
         for _ in range(random.randint(0, 2 * n))]
    T = random.sample(verts, random.randint(0, min(n, 3)))
    rows, _ = build_rows(G, R)
    T0 = set(idx[t] for t in T)
    ok, _ = force(rows, n, T0)
    if not ok:
        continue
    den = n - len(T0)
    if den <= 0:
        continue
    checked += 1
    sc = Fraction(G.m + len(R), den)
    if sc < 2:
        viol += 1
        print("VIOLATION", d, f, R, T, sc)
print(f"{checked} successful two-slope objects checked, {viol} with score < 2")
assert viol == 0
print("PASS: two-slope theorem holds on every sampled instance")
