"""
Arithmetic Kakeya -- Katz/Tao constructible-graph formalism, in the exact
"Verifiable Set-up" of the Epoch FrontierMath open problem
    https://epoch.ai/frontiermath/open-problems/arithmetic-kakeya

Objects
-------
X  : finite subset of Z^2 with (0,0) in X and a+b != 0 for every other (a,b) in X.
     (X is a set of *slopes* in homogeneous coordinates: (1,r) <-> slope r,
      (0,1) <-> slope oo.  The target direction is tau = (1,-1) <-> slope -1.)
G  : d_1,...,d_k  plus functions f_i : d_1 x ... x d_{i-1} x (d_i - 1) -> X
     Vertices are tuples e = (e_1,...,e_k) with 1 <= e_i <= d_i.
     n(G) = d_1...d_k
     m(G) = sum_i sum_{e in dom f_i} [f_i(e) != (0,0)] * d_{i+1}...d_k
(R,T): R = list of single-support functions V -> X (i.e. pairs (vertex, label)),
       T = list of vertices.
Score  S = (m + |R|) / (n - |T|).

Forcing
-------
Let M be the Z-module generated by
   * the edge functions  e1 |-> x, e2 |-> -x   for each edge {e1,e2} labelled x,
   * the elements of R.
A vertex v not in T may be added to T iff some f in M has support inside
T u {v} and f(v) = (a,-a) with a != 0.  Iterate until T = V (success) or
no move is available (failure).

Because M is a Z-module and we only need *some* nonzero multiple of (1,-1),
the question "is there such an f" is a Q-linear-algebra question: scaling a
rational solution by its common denominator lands back in M.  So all the
linear algebra below is over a field (either F_p for speed, or Q for the
certificate).
"""

from fractions import Fraction
from itertools import product
from math import prod
import numpy as np

ZERO = (0, 0)
TAU = (1, -1)          # the target direction ("slope -1")
DEFAULT_P = 2147483647  # 2^31 - 1, prime


# --------------------------------------------------------------------------
# validity of X
# --------------------------------------------------------------------------
def check_X(X):
    X = [tuple(x) for x in X]
    errs = []
    if ZERO not in X:
        errs.append("(0,0) must be an element of X")
    if len(set(X)) != len(X):
        errs.append("X has repeated elements")
    for (a, b) in X:
        if (a, b) == ZERO:
            continue
        if a + b == 0:
            errs.append(f"({a},{b}) in X has a+b = 0 (forbidden)")
    return errs


# --------------------------------------------------------------------------
# the constructible graph
# --------------------------------------------------------------------------
class ConstructibleGraph:
    """d_1..d_k together with the gluing functions f_1..f_k."""

    def __init__(self, X, d, f):
        self.X = [tuple(x) for x in X]
        self.d = list(d)
        self.k = len(self.d)
        # f is a list of k dicts; f[i-1] : tuples of length i -> label
        self.f = [dict((tuple(kk), tuple(vv)) for kk, vv in fi.items()) for fi in f]
        if len(self.f) != self.k:
            raise ValueError("need exactly k gluing functions")
        self._verts = None
        self._index = None

    # ---- basic combinatorics -------------------------------------------
    @property
    def n(self):
        return prod(self.d) if self.d else 1

    @property
    def m(self):
        tot = 0
        for i in range(1, self.k + 1):
            mult = prod(self.d[i:]) if i < self.k else 1
            for key, lab in self.f[i - 1].items():
                if tuple(lab) != ZERO:
                    tot += mult
        return tot

    def vertices(self):
        if self._verts is None:
            self._verts = list(product(*[range(1, di + 1) for di in self.d]))
            self._index = {v: j for j, v in enumerate(self._verts)}
        return self._verts

    def index(self, v):
        self.vertices()
        return self._index[v]

    def validate(self):
        errs = check_X(self.X)
        Xs = set(self.X)
        for di in self.d:
            if di < 1:
                errs.append(f"d_i = {di} must be >= 1")
        for i in range(1, self.k + 1):
            for key, lab in self.f[i - 1].items():
                if len(key) != i:
                    errs.append(f"f_{i} key {key} has wrong length")
                    continue
                for j in range(i - 1):
                    if not (1 <= key[j] <= self.d[j]):
                        errs.append(f"f_{i} key {key}: coord {j+1} out of range")
                if not (1 <= key[i - 1] <= self.d[i - 1] - 1):
                    errs.append(f"f_{i} key {key}: last coord must be in 1..d_{i}-1")
                if tuple(lab) not in Xs:
                    errs.append(f"f_{i}{key} label {lab} not in X")
        return errs

    def edges(self, permissive=False):
        """List of (u, v, label).

        Default (sound) reading of operation 1: the edge produced by
        f_i(a_1..a_i) joins (a_1..a_i, c) to (a_1..a_i + 1, c) for each common
        suffix c -- exactly d_{i+1}...d_k edges, which is what m(G) counts.
        `permissive=True` implements the literal reading of the problem text
        in which the suffixes of e1 and e2 need not agree; it is a strictly
        larger operation set and is only used for exploration, never for a
        certified score.
        """
        out = []
        for i in range(1, self.k + 1):
            tail_ranges = [range(1, dj + 1) for dj in self.d[i:]]
            for key, lab in self.f[i - 1].items():
                lab = tuple(lab)
                if lab == ZERO:
                    continue
                head1 = tuple(key)
                head2 = tuple(key[:-1]) + (key[-1] + 1,)
                if not permissive:
                    for tail in product(*tail_ranges):
                        out.append((head1 + tail, head2 + tail, lab))
                else:
                    for t1 in product(*tail_ranges):
                        for t2 in product(*tail_ranges):
                            out.append((head1 + t1, head2 + t2, lab))
        return out


# --------------------------------------------------------------------------
# linear algebra helpers
# --------------------------------------------------------------------------
def _rref_partial_modp(aug, nc, p):
    """Row-reduce `aug` (numpy int64 array, mod p) pivoting only in the first
    `nc` columns.  Return the rows whose first `nc` entries are all zero,
    restricted to the remaining columns."""
    A = aug % p
    rows, cols = A.shape
    r = 0
    for c in range(nc):
        piv = None
        for i in range(r, rows):
            if A[i, c] % p:
                piv = i
                break
        if piv is None:
            continue
        if piv != r:
            A[[r, piv]] = A[[piv, r]]
        inv = pow(int(A[r, c]), p - 2, p)
        A[r] = (A[r] * inv) % p
        col = A[r + 1:, c].copy()
        nz = np.nonzero(col)[0]
        if nz.size:
            A[r + 1 + nz] = (A[r + 1 + nz] - np.outer(col[nz], A[r])) % p
        r += 1
        if r == rows:
            break
    return A[r:, nc:] % p


def _span_contains_modp(basis_rows, target, p):
    """Is `target` (length-2 vector) in the row span of basis_rows mod p?"""
    if basis_rows.shape[0] == 0:
        return not any(t % p for t in target)
    M = np.vstack([basis_rows % p, np.array(target, dtype=np.int64) % p])
    return _rank_modp(basis_rows, p) == _rank_modp(M, p)


def _rank_modp(A, p):
    A = (A % p).astype(np.int64).copy()
    rows, cols = A.shape
    r = 0
    for c in range(cols):
        piv = None
        for i in range(r, rows):
            if A[i, c] % p:
                piv = i
                break
        if piv is None:
            continue
        if piv != r:
            A[[r, piv]] = A[[piv, r]]
        inv = pow(int(A[r, c]), p - 2, p)
        A[r] = (A[r] * inv) % p
        col = A[r + 1:, c].copy()
        nz = np.nonzero(col)[0]
        if nz.size:
            A[r + 1 + nz] = (A[r + 1 + nz] - np.outer(col[nz], A[r])) % p
        r += 1
        if r == rows:
            break
    return r


def _rref_partial_exact(aug, nc):
    """Same as _rref_partial_modp but over Q (list of lists of Fraction)."""
    A = [row[:] for row in aug]
    rows = len(A)
    cols = len(A[0]) if rows else 0
    r = 0
    for c in range(nc):
        piv = None
        for i in range(r, rows):
            if A[i][c] != 0:
                piv = i
                break
        if piv is None:
            continue
        A[r], A[piv] = A[piv], A[r]
        inv = Fraction(1, 1) / A[r][c]
        A[r] = [x * inv for x in A[r]]
        for i in range(r + 1, rows):
            if A[i][c] != 0:
                fac = A[i][c]
                A[i] = [a - fac * b for a, b in zip(A[i], A[r])]
        r += 1
        if r == rows:
            break
    return [row[nc:] for row in A[r:]]


def _span_contains_exact(basis_rows, target):
    """Is target (len 2) in the Q-span of basis_rows (list of [Fraction,Fraction])?"""
    tgt = [Fraction(t) for t in target]
    rows = [row[:] for row in basis_rows if any(x != 0 for x in row)]
    # 2-dimensional: brute force
    if not rows:
        return all(t == 0 for t in tgt)
    # reduce
    piv = []
    work = [r[:] for r in rows]
    r = 0
    for c in range(2):
        p_i = None
        for i in range(r, len(work)):
            if work[i][c] != 0:
                p_i = i
                break
        if p_i is None:
            continue
        work[r], work[p_i] = work[p_i], work[r]
        inv = Fraction(1, 1) / work[r][c]
        work[r] = [x * inv for x in work[r]]
        for i in range(len(work)):
            if i != r and work[i][c] != 0:
                fac = work[i][c]
                work[i] = [a - fac * b for a, b in zip(work[i], work[r])]
        piv.append(c)
        r += 1
    v = tgt[:]
    for j, c in enumerate(piv):
        if v[c] != 0:
            fac = v[c]
            v = [a - fac * b for a, b in zip(v, work[j])]
    return all(x == 0 for x in v)


# --------------------------------------------------------------------------
# the forcing engine
# --------------------------------------------------------------------------
class ForcingProblem:
    def __init__(self, G, R, T, permissive=False):
        self.G = G
        self.R = [(tuple(v), tuple(x)) for (v, x) in R]
        self.T0 = [tuple(t) for t in T]
        self.permissive = permissive
        self.verts = G.vertices()
        self.n = len(self.verts)
        self.idx = {v: j for j, v in enumerate(self.verts)}
        self._rows = None

    # generator matrix: one row per generator, 2n columns (2 per vertex)
    def generator_rows(self):
        if self._rows is None:
            rows = []
            for (u, v, x) in self.G.edges(permissive=self.permissive):
                row = [0] * (2 * self.n)
                iu, iv = self.idx[u], self.idx[v]
                row[2 * iu] += x[0]; row[2 * iu + 1] += x[1]
                row[2 * iv] -= x[0]; row[2 * iv + 1] -= x[1]
                rows.append(row)
            for (w, x) in self.R:
                row = [0] * (2 * self.n)
                iw = self.idx[w]
                row[2 * iw] += x[0]; row[2 * iw + 1] += x[1]
                rows.append(row)
            self._rows = rows
        return self._rows

    # ---- fast local rule (sound, incomplete) ---------------------------
    def _local_round(self, T):
        """Force everything reachable by the 'two independent labels arriving
        from T (or from generators at v)' rule.  Sound but not complete."""
        from math import gcd
        adj = {}
        for (u, v, x) in self.G.edges(permissive=self.permissive):
            adj.setdefault(u, []).append((v, x))
            adj.setdefault(v, []).append((u, x))
        gens = {}
        for (w, x) in self.R:
            gens.setdefault(w, []).append(x)
        changed = True
        while changed:
            changed = False
            for v in self.verts:
                if v in T:
                    continue
                labs = list(gens.get(v, []))
                for (u, x) in adj.get(v, []):
                    if u in T:
                        labs.append(x)
                if _lattice_hits_tau(labs):
                    T.add(v)
                    changed = True
        return T

    # ---- exact / mod-p complete test -----------------------------------
    def _can_force(self, v, T, backend, p):
        """Is there f in M with supp(f) <= T u {v} and f(v) = (a,-a), a != 0?"""
        rows = self.generator_rows()
        inside = set(self.idx[t] for t in T)
        iv = self.idx[v]
        out_cols = []
        for j in range(self.n):
            if j == iv or j in inside:
                continue
            out_cols.extend([2 * j, 2 * j + 1])
        e_cols = [2 * iv, 2 * iv + 1]
        if backend == "modp":
            A = np.array(rows, dtype=np.int64)
            aug = np.concatenate([A[:, out_cols], A[:, e_cols]], axis=1) if out_cols \
                else A[:, e_cols]
            nc = len(out_cols)
            basis = _rref_partial_modp(aug, nc, p)
            return _span_contains_modp(basis, TAU, p)
        else:
            aug = [[Fraction(r[c]) for c in out_cols] + [Fraction(r[c]) for c in e_cols]
                   for r in rows]
            basis = _rref_partial_exact(aug, len(out_cols))
            return _span_contains_exact(basis, TAU)

    def run(self, backend="exact", p=DEFAULT_P, use_local=True, trace=False):
        """Return (success, T_final, log)."""
        T = set(self.T0)
        log = []
        if use_local:
            before = len(T)
            T = self._local_round(T)
            if len(T) > before:
                log.append(f"local rule: forced {len(T)-before} vertices "
                           f"(|T| = {len(T)}/{self.n})")
        while len(T) < self.n:
            progress = False
            for v in self.verts:
                if v in T:
                    continue
                if self._can_force(v, T, backend, p):
                    T.add(v)
                    log.append(f"forced {v}  (|T| = {len(T)}/{self.n})")
                    progress = True
                    if use_local:
                        b = len(T)
                        T = self._local_round(T)
                        if len(T) > b:
                            log.append(f"  local cascade: +{len(T)-b} "
                                       f"(|T| = {len(T)}/{self.n})")
                    break
            if not progress:
                stuck = [v for v in self.verts if v not in T]
                log.append(f"STUCK with {len(stuck)} vertices unforced, e.g. {stuck[:5]}")
                return False, T, log
        log.append("SUCCESS: T = V")
        return True, T, log


def _lattice_hits_tau(labels):
    """Does the Z-span of `labels` (list of Z^2 vectors) contain (a,-a), a != 0?
    Equivalent over Q: is (1,-1) in the Q-span?"""
    labels = [l for l in labels if tuple(l) != ZERO]
    if not labels:
        return False
    # rank over Q
    a = labels[0]
    for b in labels[1:]:
        if a[0] * b[1] - a[1] * b[0] != 0:
            return True          # rank 2 => contains (1,-1) up to scaling
    # rank 1: contains (a,-a) iff the direction is (1,-1)
    return a[0] + a[1] == 0


# --------------------------------------------------------------------------
# top-level scorer
# --------------------------------------------------------------------------
def score(X, d, f, T, R, backend="exact", p=DEFAULT_P, permissive=False,
          verbose=False):
    """Full verification + score.  Returns a dict."""
    G = ConstructibleGraph(X, d, f)
    errs = G.validate()
    for (w, x) in R:
        if tuple(x) not in set(G.X) or tuple(x) == ZERO:
            errs.append(f"generator label {x} not a nonzero element of X")
        if tuple(w) not in set(G.vertices()):
            errs.append(f"generator vertex {w} not a vertex")
    for t in T:
        if tuple(t) not in set(G.vertices()):
            errs.append(f"T element {t} not a vertex")
    res = {"errors": errs, "n": G.n, "m": G.m, "r": len(R), "t": len(set(map(tuple, T)))}
    if errs:
        res["ok"] = False
        return res
    fp = ForcingProblem(G, R, T, permissive=permissive)
    ok, Tf, log = fp.run(backend=backend, p=p)
    res["ok"] = ok
    res["log"] = log
    den = res["n"] - res["t"]
    res["score"] = Fraction(res["m"] + res["r"], den) if den > 0 else None
    if verbose:
        for line in log:
            print("   ", line)
    return res


# --------------------------------------------------------------------------
# serialisation in Epoch's six-line answer format
# --------------------------------------------------------------------------
def serialise(X, d, f, T, R, sc):
    lines = []
    n = prod(d) if d else 1
    G = ConstructibleGraph(X, d, f)
    lines.append(f"score = {sc}   m = {G.m}, |R| = {len(R)}, n = {G.n}, |T| = {len(T)}")
    lines.append(str([list(x) for x in X]))
    lines.append(str(list(d)))
    lines.append(str([{tuple(k): tuple(v) for k, v in fi.items()} for fi in f]))
    lines.append(str([tuple(t) for t in T]))
    lines.append(str([{tuple(w): tuple(x)} for (w, x) in R]))
    return "\n".join(lines)


# ==========================================================================
# FAST ENGINE
# --------------------------------------------------------------------------
# Key reformulation.  Let W = Q-span of the generator rows inside Q^{2n},
# let T be the currently forced set and U = V \ T.  Let W|_U be the image of
# W under restriction to the coordinates of U.  Then
#
#     v in U can be forced  <=>  delta_v (x) tau  lies in  W|_U .
#
# ("=>": lift the witness; "<=": the lift vanishes on U\{v}, i.e. its support
# is inside T u {v}, and its value at v is tau.)  So one row reduction of the
# (m+r) x 2|U| matrix per round answers the question for *every* candidate at
# once -- instead of one elimination per candidate.
# ==========================================================================

def rref_modp(A, p):
    """Full RREF mod p.  Returns (R, pivots)."""
    A = (np.asarray(A, dtype=np.int64) % p).copy()
    rows, cols = A.shape
    piv = []
    r = 0
    for c in range(cols):
        if r >= rows:
            break
        nz = np.nonzero(A[r:, c] % p)[0]
        if nz.size == 0:
            continue
        i = r + int(nz[0])
        if i != r:
            A[[r, i]] = A[[i, r]]
        inv = pow(int(A[r, c]), p - 2, p)
        A[r] = (A[r] * inv) % p
        col = A[:, c].copy()
        col[r] = 0
        nzr = np.nonzero(col)[0]
        if nzr.size:
            A[nzr] = (A[nzr] - np.outer(col[nzr], A[r])) % p
        piv.append(c)
        r += 1
    return A[:r], piv


def in_rowspace_modp(vec, R, piv, p):
    v = np.asarray(vec, dtype=np.int64) % p
    for j, c in enumerate(piv):
        if v[c]:
            v = (v - v[c] * R[j]) % p
    return not np.any(v % p)


def rref_exact(A):
    A = [[Fraction(x) for x in row] for row in A]
    rows = len(A)
    cols = len(A[0]) if rows else 0
    piv = []
    r = 0
    for c in range(cols):
        if r >= rows:
            break
        i = None
        for j in range(r, rows):
            if A[j][c] != 0:
                i = j
                break
        if i is None:
            continue
        A[r], A[i] = A[i], A[r]
        inv = Fraction(1) / A[r][c]
        A[r] = [x * inv for x in A[r]]
        for j in range(rows):
            if j != r and A[j][c] != 0:
                fac = A[j][c]
                A[j] = [a - fac * b for a, b in zip(A[j], A[r])]
        piv.append(c)
        r += 1
    return A[:r], piv


def in_rowspace_exact(vec, R, piv):
    v = [Fraction(x) for x in vec]
    for j, c in enumerate(piv):
        if v[c] != 0:
            fac = v[c]
            v = [a - fac * b for a, b in zip(v, R[j])]
    return all(x == 0 for x in v)


def fast_force(rows, n, T0_idx, backend="modp", p=DEFAULT_P, want_log=False):
    """rows: list of length-2n integer rows (module generators).
    Returns (success, forced_index_set, log)."""
    T = set(T0_idx)
    A = np.array(rows, dtype=np.int64) if rows else np.zeros((0, 2 * n), dtype=np.int64)
    log = []
    while len(T) < n:
        U = [j for j in range(n) if j not in T]
        cols = []
        for j in U:
            cols.extend([2 * j, 2 * j + 1])
        B = A[:, cols] if A.shape[0] else np.zeros((0, len(cols)), dtype=np.int64)
        if backend == "modp":
            R, piv = rref_modp(B, p)
        else:
            R, piv = rref_exact(B.tolist())
        found = None
        for i, j in enumerate(U):
            tgt = [0] * len(cols)
            tgt[2 * i] = TAU[0]
            tgt[2 * i + 1] = TAU[1]
            ok = (in_rowspace_modp(tgt, R, piv, p) if backend == "modp"
                  else in_rowspace_exact(tgt, R, piv))
            if ok:
                found = j
                break
        if found is None:
            if want_log:
                log.append(f"STUCK at |T| = {len(T)}/{n}")
            return False, T, log
        T.add(found)
        if want_log:
            log.append(f"forced index {found} (|T| = {len(T)}/{n})")
    if want_log:
        log.append("SUCCESS")
    return True, T, log


def build_rows(G, R, permissive=False):
    verts = G.vertices()
    idx = {v: j for j, v in enumerate(verts)}
    n = len(verts)
    rows = []
    for (u, v, x) in G.edges(permissive=permissive):
        row = [0] * (2 * n)
        iu, iv = idx[u], idx[v]
        row[2 * iu] += x[0]; row[2 * iu + 1] += x[1]
        row[2 * iv] -= x[0]; row[2 * iv + 1] -= x[1]
        rows.append(row)
    for (w, x) in R:
        row = [0] * (2 * n)
        iw = idx[tuple(w)]
        row[2 * iw] += x[0]; row[2 * iw + 1] += x[1]
        rows.append(row)
    return rows, idx


def score_fast(X, d, f, T, R, backend="modp", p=DEFAULT_P, permissive=False):
    G = ConstructibleGraph(X, d, f)
    rows, idx = build_rows(G, R, permissive)
    T0 = set(idx[tuple(t)] for t in T)
    ok, Tf, log = fast_force(rows, G.n, T0, backend=backend, p=p, want_log=True)
    den = G.n - len(T0)
    return {"ok": ok, "n": G.n, "m": G.m, "r": len(R), "t": len(T0),
            "score": Fraction(G.m + len(R), den) if den > 0 else None, "log": log}


# --------------------------------------------------------------------------
# parse Epoch's six-line answer format back into an object (round-trip check)
# --------------------------------------------------------------------------
def parse_answer(text):
    """Inverse of serialise().  Lines: 1 human summary, 2 X, 3 d, 4 f, 5 T, 6 R."""
    import ast
    lines = [ln for ln in text.strip().splitlines() if ln.strip()]
    if len(lines) < 6:
        raise ValueError("expected six lines")
    X = [tuple(x) for x in ast.literal_eval(lines[1])]
    d = list(ast.literal_eval(lines[2]))
    f_raw = ast.literal_eval(lines[3])
    f = [{tuple(k): tuple(v) for k, v in fi.items()} for fi in f_raw]
    T = [tuple(t) for t in ast.literal_eval(lines[4])]
    R_raw = ast.literal_eval(lines[5])
    R = []
    for dd in R_raw:
        for k, v in dd.items():
            R.append((tuple(k), tuple(v)))
    return X, d, f, T, R


def verify_answer(text, bound=None, backend="exact"):
    """Full independent check of a submitted answer string."""
    X, d, f, T, R = parse_answer(text)
    res = score(X, d, f, T, R, backend=backend)
    res["within_bound"] = None if bound is None else (
        res["score"] is not None and res["ok"] and res["score"] <= Fraction(bound))
    return res
